#!/bin/bash

FILE=".git/hooks/pre-commit"
SEARCH_TERM="File generated by pre-commit"

if [ -f "$FILE" ]; then
    if grep -q "$SEARCH_TERM" "$FILE"; then
        echo "Success: $FILE exists and is managed by pre-commit."
        exit 0
    else
        echo "Notice: $FILE exists, but it is not managed by" \
	      "pre-commit, please run 'pre-commit install'"
        exit 1
    fi
else
    echo "Error: $FILE not found. Please run 'pre-commit install'" \
         "to generate '.git/hooks/pre-commit' "
    exit 1
fi
